language: python
cache: pip
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
    - varnish
install:
  - "pip install -r requirements.txt"
  - "make ci"
before_script:
script: ansible-playbook -i ./hosts test-varnishadm.yml
